### ISSUE TITLE
What happens if config file has wrong format ?

### ISSUE THREAD

**Issue by NiharZanwar** [Sharanya-Ranka/Temple-Image-Analytics#1]
https://github.com/Sharanya-Ranka/Temple-Image-Analytics/blob/15f8ab3ad49bcbc29ed42227adfafb776b7d3e12/flask_server.py#L190

@Sharanya-Ranka Please verify.

**Comment by Sharanya-Ranka** [comment]
Currently, as a try except block is not used in the parse_config_json() function, if an error occurs, the program control is terminated, and the flask app doesn't start.

Errors could occur in 2 ways
1. The config file is not in json format. Currently, JSONDecodeError is raised
2. The file is in json format, but the required keys are not provided. Currently, KeyError is raised

In both these cases, the program simply terminates. Checking a config file is a one-time process and if it works once, it will continue to work until the file is changed.  I don't think the file contents need to be changed once it works(in the Docker), therefore, I haven't made any special handling of these errors.

If it is preferred to have special handling/error messages, please tell me what is needed and I will change it accordingly.

**Comment by NiharZanwar** [comment]
How do I know that an error has occurred because the directory where you store logs is written in the config file? The program needs to know where to store the error when there is no error file

**Comment by Sharanya-Ranka** [comment]
The errors come on the console output. I had assumed that the flask server would be started manually and then the requests would be handled automatically.
If it will be done automatically, I need to assume some structure of the directory for the logs. As per the docker directory structure we discussed, it would be ```config_file_path->parent->parent->logs->error_log.txt```. I can add that, but then the errors would be silent i.e. no indication of failure would be given to the caller (unless I raise another error in the except clause).
If I get more info on how the flask app would be called by an external script, I could work on a better solution
